Add : 회원가입 기능 추가, 회원가입 기능 테스트 추가
wecode-bootcamp-korea/18-2nd-Heuream-backend pull request #12
Opened 2021-04-06 17:23 UTC by KIMGYUDONG

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 추가, 회원가입 기능 테스트 추가
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- account/views.py에 `UserSignUp`클래스에 회원 가입 기능 추가했습니다. 이메일 형식, 비밀번호 형식, 등록된 이메일인지, 키와 값이 전달됐는지에 대해 검사했습니다.
- account/test.py에 `SignUpTest`클래스에 성공과 에러메시지에 대한 테스트를 작성했습니다.

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 오류가 나서 account/test.py에 `SignUpTest`클래스에 TestCase가 아니라 TransactionTestCasef를 상속시켰는데, 정확한 사용법을 모르겠습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-04-07 09:34 UTC, jamessoun93 requested changes

2021-04-07 09:34 UTC, jamessoun93 commented on account/views.py
> +            if not bool(re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email)):
규동님 이 부분 bool() 없이도 falsy, truthy 값으로 인식되서 필요 없을거에요! 테스트해보세요!

2021-04-07 09:34 UTC, jamessoun93 commented on account/views.py
> +            if not (MIN_PASSWORD_LENGTH <= len(password) <= MAX_PASSWORD_LENGTH and re.findall('[0-9]+', password) and re.findall('[a-zA-Z]+', password) and re.findall('[`~!@#$%^&*(),<.>/?]+', passwo
이 부분 가독성이 너무 안좋은데, regex 사용하는 부분은 통합해주세요.

2021-04-07 09:34 UTC, jamessoun93 commented on account/views.py
> +                size = Size.objects.get(size=size)
data.get() 사용하신 후 아래에서 해당 필드 None 으로 넣으시면 없이 들어갑니다!
그러면 불필요한 if 문 사라져서 지금보다 가독성이 좋아지는 효과가 있겠네요!

2021-04-07 09:34 UTC, jamessoun93 commented on account/views.py
> +                )
위에서 말씀드린 아래부분이 여기입니다!

2021-04-07 11:26 UTC, KIMGYUDONG commented on account/views.py
> +            if not bool(re.match('^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$', email)):
오오 오오 감사합니당

2021-04-07 11:26 UTC, KIMGYUDONG commented on account/views.py
> +            if not (MIN_PASSWORD_LENGTH <= len(password) <= MAX_PASSWORD_LENGTH and re.findall('[0-9]+', password) and re.findall('[a-zA-Z]+', password) and re.findall('[`~!@#$%^&*(),<.>/?]+', passwo
넵넵 완전 다 통합해버렸습니다. 구선생 화이팅!

2021-04-07 11:27 UTC, KIMGYUDONG commented on account/views.py
> +                size = Size.objects.get(size=size)
오 
진짜 코드가 숭덩숭덩 날라가네요 감사합니다!

2021-04-07 11:27 UTC, KIMGYUDONG commented on account/views.py
> +                )
수정했습니다 감사합니다

2021-04-08 01:16 UTC, jamessoun93 commented on account/views.py
> +                size = Size.objects.get(size=size)
음 규동님 근데 size 부분을 create 할때 아예 같이 없애버리셨는데요?!

2021-04-08 01:23 UTC, jamessoun93 commented on account/views.py
> +                size = Size.objects.get(size=size)
@KIMGYUDONG

2021-04-08 02:29 UTC, KIMGYUDONG commented on account/views.py
> +                size = Size.objects.get(size=size)
엇,, size 없는걸 삭제해야하는데 헷갈렸네요 수정하겠습니다 감사합니다!

2021-04-08 02:43 UTC, KIMGYUDONG commented on account/views.py
> +                size = Size.objects.get(size=size)
수정했습니다!

2021-04-08 02:54 UTC, jamessoun93 approved these changes

2021-04-08 02:54 UTC, merged