[흐림 허정원] 상품 필터링,정렬 기능 구현
wecode-bootcamp-korea/18-2nd-Heuream-backend pull request #5
Opened 2021-04-03 09:08 UTC by HurJungWon

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 상품 필터링, 정렬 후 리스트 전달 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 브랜드, 브랜드라인, 서브라인, 사이즈 별로 필터 기능
- 인기순, 낮은구매가격순, 최근발매일순, 발매가격순 으로 정렬 기능
- 회원, 비회원 인증 후 상품 위시리스트 상태 표시

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
-

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-04-05 02:20 UTC, jamessoun93 requested changes

2021-04-05 02:20 UTC, jamessoun93 commented on product/views.py
> +            serch      = request.GET.get('q')
```suggestion
            search      = request.GET.get('q')
```

2021-04-05 02:20 UTC, jamessoun93 commented on product/views.py
> +            sort       = request.GET.get('sort')
각 필터 다중 선택은 불가능한가요?

2021-04-05 02:20 UTC, jamessoun93 commented on product/views.py
> +                serch_list.append(Q(korean_name__icontains=serch)|Q(english_name__icontains=serch)|Q(models_number__icontains=serch)|Q(brand__name__icontains=serch)|Q(brand_line__name__icontains=serc
```suggestion
            search_list = []
            if search:
                search_list.append(Q(korean_name__icontains=search)|Q(english_name__icontains=search)|Q(models_number__icontains=search)|Q(brand__name__icontains=search)|Q(brand_line__name__icontains=search)|Q(sub_line__name__icontains=search))
```
이렇게 길어지는경우 멀티라인으로 변경해서 가독성 좋게 만들어주세요!

2021-04-05 02:20 UTC, jamessoun93 commented on product/views.py
> +            products = Product.objects.filter(*serch_list,**filter).annotate(price=Min('productsize__bidding__price')).order_by(*sort_list)[OFFSET:LIMIT]
이 부분도 멀티라인으로 깔끔하게 변경해주세요!

2021-04-05 03:50 UTC, HurJungWon commented on product/views.py
> +            serch      = request.GET.get('q')
ㅎㅎㅎㅎ...

2021-04-05 03:56 UTC, HurJungWon commented on product/views.py
> +            sort       = request.GET.get('sort')
확인해본 결과 웹에서는 다중 선택이 불가능한데 앱에서는 가능합니다. 다중선택 가능하게 한번 만들어보겠습니다!!

2021-04-07 02:08 UTC, jamessoun93 approved these changes

2021-04-07 02:08 UTC, merged